// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdomfbxshshvfbprfnfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkb21mYnhzaHNodmZicHJmbmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjA0NTksImV4cCI6MjA3MzM5NjQ1OX0.YmFO9vfVVNdgW35dQAi18IR9Lea66EHzj3H_UKR2n1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});